const scale = {
  one:   '0.75rem',
  two:   '0.875rem',
  three: '1rem',
  four:  '1.25rem',
  five:  '1.5rem',
  six:   '2rem',
}

export default {
  p1:  { padding: scale.one },
  pt1: { paddingTop: scale.one },
  pb1: { paddingBottom: scale.one },
  pl1: { paddingLeft: scale.one },
  pr1: { paddingRight: scale.one },
  px1: { paddingLeft: scale.one, paddingRight: scale.one },
  py1: { paddingTop: scale.one, paddingBottom: scale.one },

  p2:  { padding: scale.two },
  pt2: { paddingTop: scale.two },
  pb2: { paddingBottom: scale.two },
  pl2: { paddingLeft: scale.two },
  pr2: { paddingRight: scale.two },
  px2: { paddingLeft: scale.two, paddingRight: scale.two },
  py2: { paddingTop: scale.two, paddingBottom: scale.two },

  p3:  { padding: scale.three },
  pt3: { paddingTop: scale.three },
  pb3: { paddingBottom: scale.three },
  pl3: { paddingLeft: scale.three },
  pr3: { paddingRight: scale.three },
  px3: { paddingLeft: scale.three, paddingRight: scale.three },
  py3: { paddingTop: scale.three, paddingBottom: scale.three },

  p4:  { padding: scale.four },
  pt4: { paddingTop: scale.four },
  pb4: { paddingBottom: scale.four },
  pl4: { paddingLeft: scale.four },
  pr4: { paddingRight: scale.four },
  px4: { paddingLeft: scale.four, paddingRight: scale.four },
  py4: { paddingTop: scale.four, paddingBottom: scale.four },

  p5:  { padding: scale.five },
  pt5: { paddingTop: scale.five },
  pb5: { paddingBottom: scale.five },
  pl5: { paddingLeft: scale.five },
  pr5: { paddingRight: scale.five },
  px5: { paddingLeft: scale.five, paddingRight: scale.five },
  py5: { paddingTop: scale.five, paddingBottom: scale.five },

  p6:  { padding: scale.six },
  pt6: { paddingTop: scale.six },
  pb6: { paddingBottom: scale.six },
  pl6: { paddingLeft: scale.six },
  pr6: { paddingRight: scale.six },
  px6: { paddingLeft: scale.six, paddingRight: scale.six },
  py6: { paddingTop: scale.six, paddingBottom: scale.six },

  m1:  { margin: scale.one },
  mt1: { marginTop: scale.one },
  mb1: { marginBottom: scale.one },
  ml1: { marginLeft: scale.one },
  mr1: { marginRight: scale.one },
  mx1: { marginLeft: scale.one, marginRight: scale.one },
  my1: { marginTop: scale.one, marginBottom: scale.one },

  m2:  { margin: scale.two },
  mt2: { marginTop: scale.two },
  mb2: { marginBottom: scale.two },
  ml2: { marginLeft: scale.two },
  mr2: { marginRight: scale.two },
  mx2: { marginLeft: scale.two, marginRight: scale.two },
  my2: { marginTop: scale.two, marginBottom: scale.two },

  m3:  { margin: scale.three },
  mt3: { marginTop: scale.three },
  mb3: { marginBottom: scale.three },
  ml3: { marginLeft: scale.three },
  mr3: { marginRight: scale.three },
  mx3: { marginLeft: scale.three, marginRight: scale.three },
  my3: { marginTop: scale.three, marginBottom: scale.three },

  m4:  { margin: scale.four },
  mt4: { marginTop: scale.four },
  mb4: { marginBottom: scale.four },
  ml4: { marginLeft: scale.four },
  mr4: { marginRight: scale.four },
  mx4: { marginLeft: scale.four, marginRight: scale.four },
  my4: { marginTop: scale.four, marginBottom: scale.four },

  m5:  { margin: scale.five },
  mt5: { marginTop: scale.five },
  mb5: { marginBottom: scale.five },
  ml5: { marginLeft: scale.five },
  mr5: { marginRight: scale.five },
  mx5: { marginLeft: scale.five, marginRight: scale.five },
  my5: { marginTop: scale.five, marginBottom: scale.five },

  m6:  { margin: scale.six },
  mt6: { marginTop: scale.six },
  mb6: { marginBottom: scale.six },
  ml6: { marginLeft: scale.six },
  mr6: { marginRight: scale.six },
  mx6: { marginLeft: scale.six, marginRight: scale.six },
  my6: { marginTop: scale.six, marginBottom: scale.six },
}

